#!/bin/sh
set -e

case "$1" in
    remove)
        # Reload systemd daemon
        systemctl daemon-reload || true

        # Remove ipsets directory
        rm -rf /etc/llx-external-routes/ipsets
        ;;
    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#
